# Generated by Django 5.2.4 on 2025-07-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='my_score',
            field=models.FloatField(default=0.0),
        ),
    ]
