# Generated by Django 5.2.4 on 2025-07-18 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_my_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='my_score',
        ),
    ]
