# Generated by Django 5.2.4 on 2025-07-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_latitude_job_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='number_of_workers',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('plumber', 'Plumber'), ('electrician', 'Electrician'), ('mistri', 'Mistri'), ('labour', 'Labour'), ('halwai', 'Halwai'), ('saloon', 'Saloon Worker'), ('mechanic', 'Mechanic'), ('driver', 'Driver'), ('welder', 'Welder'), ('painter', 'Painter'), ('carpenter', 'Carpenter'), ('helper', 'Helper'), ('security', 'Security Guard'), ('gardener', 'Gardener'), ('cleaner', 'Cleaner'), ('cook', 'Cook'), ('other', 'Other')], max_length=20),
        ),
    ]
