# Generated by Django 5.2.4 on 2025-07-18 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_latitude_alter_job_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='latitude',
            field=models.CharField(default='0.0', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='longitude',
            field=models.CharField(default='0.0', max_length=100),
        ),
    ]
